@hostname=localhost
@port=7124
@host={{hostname}}:{{port}}


GET https://{{host}}/api/v1/employees
Accept: application/json

###

@employeeId=6
GET https://{{host}}/api/v1/employees/{{employeeId}}
Accept: application/json

###

GET https://{{host}}/api/v1/dependents
Accept: application/json

###

@dependentId=1
GET https://{{host}}/api/v1/dependents/{{dependentId}}
Accept: application/json

###

